from __future__ import annotations

from dataclasses import dataclass
import json
import re

from .. import ir
from ..types import (
    BOOL,
    ERROR,
    STR,
    VOID,
    NamedType,
    OptionalType,
    PrimitiveType,
    TupleType,
    Type,
    is_list,
    is_task,
)


@dataclass
class CExpr:
    code: str
    prelude: list[str]


class CBackend:
    name = "c"

    def __init__(self) -> None:
        self.program: ir.IRProgram | None = None
        self.structs: dict[str, ir.IRStructDef] = {}
        self.emitted_types: set[Type] = set()
        self.emitting_types: set[Type] = set()
        self.type_lines: list[str] = []
        self.temp_counter = 0
        self.current_function: ir.IRFunction | None = None
        self.catch_targets: list[tuple[str | None, Type]] = []
        self.spawn_sites: dict[int, ir.IRSpawn] = {}

    def emit(self, program: ir.IRProgram) -> str:
        self.program = program
        self.structs = {item.name: item for item in program.structs}
        self.emitted_types.clear()
        self.emitting_types.clear()
        self.type_lines.clear()
        self.temp_counter = 0
        self.spawn_sites = self.collect_spawn_sites(program)

        lines = ["// Generated by the ZyenLang 0.2 typed C backend."]
        if "threads" in program.features:
            lines.append("#define ZY2_ENABLE_THREADS 1")
        lines.extend(['#include "zy2_runtime.h"', ""])
        for struct in program.structs:
            lines.append(f"typedef struct {self.struct_tag(struct.name)} {self.struct_c_name(struct.name)};")
        if program.structs:
            lines.append("")

        for typ in self.collect_program_types(program):
            self.emit_type_definition(typ)
        lines.extend(self.type_lines)
        if self.type_lines:
            lines.append("")

        for function in program.extern_functions:
            lines.append(self.extern_signature(function) + ";")
        if program.extern_functions:
            lines.append("")
        for function in program.functions:
            lines.append(self.function_signature(function) + ";")
        lines.append("")

        for spawn in self.spawn_sites.values():
            lines.extend(self.emit_spawn_helper(spawn))
            lines.append("")

        for function in program.functions:
            lines.extend(self.emit_function(function))
            lines.append("")

        main = next(item for item in program.functions if item.name == "main" and item.receiver_type is None)
        lines.extend(self.emit_main_wrapper(main))
        lines.append("")
        return "\n".join(lines)

    def collect_spawn_sites(self, program: ir.IRProgram) -> dict[int, ir.IRSpawn]:
        found: dict[int, ir.IRSpawn] = {}

        def expression(value: ir.IRExpr) -> None:
            if isinstance(value, ir.IRSpawn):
                found[value.spawn_id] = value
                expression(value.call)
            elif isinstance(value, ir.IRAwait):
                expression(value.task)
            elif isinstance(value, ir.IROptionalSome):
                expression(value.value)
            elif isinstance(value, ir.IRUnary):
                expression(value.operand)
            elif isinstance(value, ir.IRBinary):
                expression(value.left)
                expression(value.right)
            elif isinstance(value, ir.IRField):
                expression(value.receiver)
            elif isinstance(value, ir.IRCall):
                for arg in value.args:
                    expression(arg)
            elif isinstance(value, (ir.IRTuple, ir.IRList)):
                for item in value.items:
                    expression(item)
            elif isinstance(value, ir.IRStruct):
                for _, item in value.fields:
                    expression(item)
            elif isinstance(value, ir.IRCatch):
                expression(value.value)
                block(value.handler)

        def statement(value: ir.IRStmt) -> None:
            if isinstance(value, ir.IRLet):
                expression(value.value)
            elif isinstance(value, (ir.IRReturn, ir.IRRecover)) and value.value is not None:
                expression(value.value)
            elif isinstance(value, ir.IRStop):
                expression(value.error)
            elif isinstance(value, ir.IRIf):
                expression(value.condition)
                block(value.then_block)
                if value.else_block:
                    block(value.else_block)
            elif isinstance(value, ir.IRIfLet):
                expression(value.value)
                block(value.then_block)
                if value.else_block:
                    block(value.else_block)
            elif isinstance(value, ir.IRWhile):
                expression(value.condition)
                block(value.body)
            elif isinstance(value, ir.IRAssign):
                expression(value.target)
                expression(value.value)
            elif isinstance(value, ir.IRExprStmt):
                expression(value.value)

        def block(value: ir.IRBlock) -> None:
            for item in value.statements:
                statement(item)

        for function in program.functions:
            block(function.body)
        return found

    def collect_program_types(self, program: ir.IRProgram) -> list[Type]:
        found: list[Type] = []
        seen: set[Type] = set()

        def add(typ: Type) -> None:
            if typ in seen:
                return
            seen.add(typ)
            found.append(typ)
            if isinstance(typ, NamedType):
                for arg in typ.args:
                    add(arg)
            elif isinstance(typ, TupleType):
                for item in typ.items:
                    add(item)
            elif isinstance(typ, OptionalType):
                add(typ.inner)

        def expression(value: ir.IRExpr) -> None:
            add(value.typ)
            if isinstance(value, ir.IROptionalSome):
                expression(value.value)
            elif isinstance(value, ir.IRUnary):
                expression(value.operand)
            elif isinstance(value, ir.IRBinary):
                expression(value.left)
                expression(value.right)
            elif isinstance(value, ir.IRField):
                expression(value.receiver)
            elif isinstance(value, ir.IRCall):
                if value.throws:
                    add(value.throws)
                    add(self.result_marker(value.typ))
                for arg in value.args:
                    expression(arg)
            elif isinstance(value, (ir.IRTuple, ir.IRList)):
                for item in value.items:
                    expression(item)
            elif isinstance(value, ir.IRStruct):
                for _, item in value.fields:
                    expression(item)
            elif isinstance(value, ir.IRCatch):
                expression(value.value)
                block(value.handler)
            elif isinstance(value, ir.IRSpawn):
                expression(value.call)
            elif isinstance(value, ir.IRAwait):
                expression(value.task)

        def statement(value: ir.IRStmt) -> None:
            if isinstance(value, ir.IRLet):
                for typ in value.types:
                    add(typ)
                expression(value.value)
            elif isinstance(value, (ir.IRReturn, ir.IRRecover)) and value.value is not None:
                expression(value.value)
            elif isinstance(value, ir.IRStop):
                expression(value.error)
            elif isinstance(value, ir.IRIf):
                expression(value.condition)
                block(value.then_block)
                if value.else_block:
                    block(value.else_block)
            elif isinstance(value, ir.IRIfLet):
                expression(value.value)
                add(value.inner_type)
                block(value.then_block)
                if value.else_block:
                    block(value.else_block)
            elif isinstance(value, ir.IRWhile):
                expression(value.condition)
                block(value.body)
            elif isinstance(value, ir.IRAssign):
                expression(value.target)
                expression(value.value)
            elif isinstance(value, ir.IRExprStmt):
                expression(value.value)

        def block(value: ir.IRBlock) -> None:
            for item in value.statements:
                statement(item)

        for struct in program.structs:
            add(NamedType(struct.name))
            for field in struct.fields:
                add(field.typ)
                if field.default:
                    expression(field.default)
        for function in program.functions:
            add(function.return_type)
            if function.throws:
                add(function.throws)
                add(self.result_marker(function.return_type))
            for param in function.params:
                add(param.typ)
            block(function.body)
        for function in program.extern_functions:
            add(function.return_type)
            if function.throws:
                add(function.throws)
                add(self.result_marker(function.return_type))
            for param in function.params:
                add(param.typ)
        return found

    def result_marker(self, value_type: Type) -> NamedType:
        return NamedType("__Result", (value_type, ERROR))

    def emit_type_definition(self, typ: Type) -> None:
        if typ in self.emitted_types or isinstance(typ, PrimitiveType):
            return
        if typ in self.emitting_types:
            raise ValueError(f"recursive by-value type `{typ.display()}`")
        self.emitting_types.add(typ)
        try:
            if isinstance(typ, NamedType) and typ.name in self.structs:
                struct = self.structs[typ.name]
                for field in struct.fields:
                    self.emit_type_definition(field.typ)
                self.type_lines.append(f"struct {self.struct_tag(struct.name)} {{")
                for field in struct.fields:
                    self.type_lines.append(f"    {self.c_type(field.typ)} {self.ident(field.name)};")
                self.type_lines.append("};")
                self.type_lines.append("")
            elif is_list(typ):
                element = typ.args[0]
                if not (isinstance(element, NamedType) and element.name in self.structs):
                    self.emit_type_definition(element)
                self.type_lines.extend(
                    [
                        f"typedef struct {self.type_name(typ)} {{",
                        f"    {self.c_type(element)}* data;",
                        "    uintptr_t len;",
                        f"}} {self.type_name(typ)};",
                        "",
                    ]
                )
            elif is_task(typ):
                self.emit_type_definition(typ.args[0])
                self.type_lines.extend(
                    [
                        f"typedef struct {self.type_name(typ)} {{",
                        "    zy2_Task* control;",
                        f"}} {self.type_name(typ)};",
                        "",
                    ]
                )
            elif isinstance(typ, OptionalType):
                self.emit_type_definition(typ.inner)
                self.type_lines.extend(
                    [
                        f"typedef struct {self.type_name(typ)} {{",
                        "    bool has_value;",
                        f"    {self.c_type(typ.inner)} value;",
                        f"}} {self.type_name(typ)};",
                        "",
                    ]
                )
            elif isinstance(typ, TupleType):
                for item in typ.items:
                    self.emit_type_definition(item)
                self.type_lines.append(f"typedef struct {self.type_name(typ)} {{")
                for index, item in enumerate(typ.items):
                    self.type_lines.append(f"    {self.c_type(item)} item_{index};")
                self.type_lines.append(f"}} {self.type_name(typ)};")
                self.type_lines.append("")
            elif isinstance(typ, NamedType) and typ.name == "__Result":
                value_type = typ.args[0]
                self.emit_type_definition(value_type)
                self.type_lines.append(f"typedef struct {self.type_name(typ)} {{")
                self.type_lines.append("    bool ok;")
                if value_type != VOID:
                    self.type_lines.append(f"    {self.c_type(value_type)} value;")
                self.type_lines.append("    zy2_Error error;")
                self.type_lines.append(f"}} {self.type_name(typ)};")
                self.type_lines.append("")
            else:
                raise ValueError(f"C backend does not yet support `{typ.display()}`")
            self.emitted_types.add(typ)
        finally:
            self.emitting_types.remove(typ)

    def emit_function(self, function: ir.IRFunction) -> list[str]:
        self.current_function = function
        try:
            lines = [self.function_signature(function) + " {"]
            for param in function.params:
                lines.append(f"    (void){self.ident(param.name)};")
            lines.extend(self.emit_block(function.body, 1))
            if function.return_type == VOID and not function.throws:
                lines.append("    return;")
            elif function.return_type == VOID and function.throws:
                result = self.result_type(function.return_type)
                lines.append(f"    return ({result}){{ .ok = true }};")
            lines.append("}")
            return lines
        finally:
            self.current_function = None

    def function_signature(self, function: ir.IRFunction) -> str:
        return_type = self.result_type(function.return_type) if function.throws else self.c_type(function.return_type)
        params = ", ".join(f"{self.c_type(param.typ)} {self.ident(param.name)}" for param in function.params)
        if not params:
            params = "void"
        prefix = "static " if function.visibility == "private" else ""
        return f"{prefix}{return_type} {function.c_name}({params})"

    def extern_signature(self, function: ir.IRExternFunction) -> str:
        return_type = self.result_type(function.return_type) if function.throws else self.c_type(function.return_type)
        params = ", ".join(f"{self.c_type(param.typ)} {self.ident(param.name)}" for param in function.params)
        if not params:
            params = "void"
        return f"extern {return_type} {function.c_name}({params})"

    def emit_spawn_helper(self, expression: ir.IRSpawn) -> list[str]:
        result_type = expression.call.typ
        lines = [f"static void __zy2_spawn_{expression.spawn_id}(void* context, void* result) {{", "    (void)context;"]
        if result_type == VOID:
            lines.append("    (void)result;")
            lines.append(f"    {expression.call.target}();")
        else:
            lines.append(f"    *(({self.c_type(result_type)}*)result) = {expression.call.target}();")
        lines.append("}")
        return lines

    def emit_main_wrapper(self, main: ir.IRFunction) -> list[str]:
        lines = ["int main(int argc, char** argv) {", "    zy2_set_process_args(argc, argv);"]
        if main.throws:
            lines.append(f"    {self.result_type(main.return_type)} result = {main.c_name}();")
            lines.append("    if (!result.ok) zy2_unhandled_error(result.error);")
            lines.append("    return (int)result.value;")
        else:
            lines.append(f"    return (int){main.c_name}();")
        lines.append("}")
        return lines

    def emit_block(self, block: ir.IRBlock, indent: int) -> list[str]:
        lines: list[str] = []
        for statement in block.statements:
            lines.extend(self.emit_statement(statement, indent))
        return lines

    def emit_statement(self, statement: ir.IRStmt, indent: int) -> list[str]:
        pad = "    " * indent
        if isinstance(statement, ir.IRLet):
            value = self.emit_expr(statement.value)
            lines = [pad + line for line in value.prelude]
            if len(statement.names) == 1:
                lines.append(f"{pad}{self.c_type(statement.types[0])} {self.ident(statement.names[0])} = {value.code};")
                lines.append(f"{pad}(void){self.ident(statement.names[0])};")
            else:
                temp = self.temp("tuple")
                lines.append(f"{pad}{self.c_type(statement.value.typ)} {temp} = {value.code};")
                for index, (name, typ) in enumerate(zip(statement.names, statement.types)):
                    lines.append(f"{pad}{self.c_type(typ)} {self.ident(name)} = {temp}.item_{index};")
                    lines.append(f"{pad}(void){self.ident(name)};")
            return lines
        if isinstance(statement, ir.IRReturn):
            if statement.value is None:
                if self.current_function and self.current_function.throws:
                    return [f"{pad}return ({self.result_type(VOID)}){{ .ok = true }};"]
                return [f"{pad}return;"]
            value = self.emit_expr(statement.value)
            lines = [pad + line for line in value.prelude]
            if self.current_function and self.current_function.throws:
                result = self.result_type(self.current_function.return_type)
                lines.append(f"{pad}return ({result}){{ .ok = true, .value = {value.code} }};")
            else:
                lines.append(f"{pad}return {value.code};")
            return lines
        if isinstance(statement, ir.IRStop):
            value = self.emit_expr(statement.error)
            lines = [pad + line for line in value.prelude]
            if not self.current_function or not self.current_function.throws:
                raise ValueError("verified IR contains stop in a non-throwing function")
            result = self.result_type(self.current_function.return_type)
            lines.append(f"{pad}return ({result}){{ .ok = false, .error = {value.code} }};")
            return lines
        if isinstance(statement, ir.IRRecover):
            if not self.catch_targets:
                raise ValueError("verified IR contains recover outside catch")
            target, expected = self.catch_targets[-1]
            if statement.value is None:
                return [f"{pad}/* recovered void error */"]
            value = self.emit_expr(statement.value)
            lines = [pad + line for line in value.prelude]
            if target is None or expected == VOID:
                lines.append(f"{pad}(void)({value.code});")
            else:
                lines.append(f"{pad}{target} = {value.code};")
            return lines
        if isinstance(statement, ir.IRIf):
            condition = self.emit_expr(statement.condition)
            lines = [pad + line for line in condition.prelude]
            lines.append(f"{pad}if {self.control_condition(condition.code)} {{")
            lines.extend(self.emit_block(statement.then_block, indent + 1))
            if statement.else_block is not None:
                lines.append(f"{pad}}} else {{")
                lines.extend(self.emit_block(statement.else_block, indent + 1))
            lines.append(f"{pad}}}")
            return lines
        if isinstance(statement, ir.IRIfLet):
            value = self.emit_expr(statement.value)
            lines = [pad + line for line in value.prelude]
            temp = self.temp("optional")
            lines.append(f"{pad}{self.c_type(statement.value.typ)} {temp} = {value.code};")
            lines.append(f"{pad}if ({temp}.has_value) {{")
            lines.append(f"{pad}    {self.c_type(statement.inner_type)} {self.ident(statement.name)} = {temp}.value;")
            lines.extend(self.emit_block(statement.then_block, indent + 1))
            if statement.else_block is not None:
                lines.append(f"{pad}}} else {{")
                lines.extend(self.emit_block(statement.else_block, indent + 1))
            lines.append(f"{pad}}}")
            return lines
        if isinstance(statement, ir.IRWhile):
            condition = self.emit_expr(statement.condition)
            lines = [f"{pad}while (true) {{"]
            lines.extend("    " + pad + line for line in condition.prelude)
            lines.append(f"{pad}    if (!{self.control_condition(condition.code)}) break;")
            lines.extend(self.emit_block(statement.body, indent + 1))
            lines.append(f"{pad}}}")
            return lines
        if isinstance(statement, ir.IRAssign):
            target = self.emit_expr(statement.target)
            value = self.emit_expr(statement.value)
            lines = [pad + line for line in target.prelude + value.prelude]
            lines.append(f"{pad}{target.code} = {value.code};")
            return lines
        if isinstance(statement, ir.IRBreak):
            return [f"{pad}break;"]
        if isinstance(statement, ir.IRContinue):
            return [f"{pad}continue;"]
        if isinstance(statement, ir.IRExprStmt):
            value = self.emit_expr(statement.value)
            lines = [pad + line for line in value.prelude]
            lines.append(f"{pad}{value.code};")
            return lines
        raise ValueError(f"unsupported IR statement {type(statement).__name__}")

    @staticmethod
    def control_condition(code: str) -> str:
        value = code.strip()
        if value.startswith("(") and value.endswith(")"):
            depth = 0
            for index, char in enumerate(value):
                if char == "(":
                    depth += 1
                elif char == ")":
                    depth -= 1
                    if depth == 0 and index != len(value) - 1:
                        break
            else:
                if depth == 0:
                    return value
        return f"({value})"

    def emit_expr(self, expression: ir.IRExpr) -> CExpr:
        if isinstance(expression, ir.IRInt):
            return CExpr(str(expression.value), [])
        if isinstance(expression, ir.IRString):
            return CExpr(json.dumps(expression.value), [])
        if isinstance(expression, ir.IRBool):
            return CExpr("true" if expression.value else "false", [])
        if isinstance(expression, ir.IRNull):
            return CExpr(f"({self.c_type(expression.typ)}){{ .has_value = false }}", [])
        if isinstance(expression, ir.IROptionalSome):
            value = self.emit_expr(expression.value)
            return CExpr(
                f"({self.c_type(expression.typ)}){{ .has_value = true, .value = {value.code} }}",
                value.prelude,
            )
        if isinstance(expression, ir.IRName):
            return CExpr(self.ident(expression.name), [])
        if isinstance(expression, ir.IRUnary):
            operand = self.emit_expr(expression.operand)
            return CExpr(f"({expression.operator}{operand.code})", operand.prelude)
        if isinstance(expression, ir.IRBinary):
            return self.emit_binary(expression)
        if isinstance(expression, ir.IRField):
            receiver = self.emit_expr(expression.receiver)
            return CExpr(f"({receiver.code}).{self.ident(expression.name)}", receiver.prelude)
        if isinstance(expression, ir.IRCall):
            return self.emit_call(expression, propagate=True)
        if isinstance(expression, ir.IRTuple):
            return self.emit_aggregate(expression.typ, expression.items, [f"item_{i}" for i in range(len(expression.items))])
        if isinstance(expression, ir.IRList):
            return self.emit_list(expression)
        if isinstance(expression, ir.IRStruct):
            values = tuple(value for _, value in expression.fields)
            names = [self.ident(name) for name, _ in expression.fields]
            return self.emit_aggregate(expression.typ, values, names)
        if isinstance(expression, ir.IRCatch):
            return self.emit_catch(expression)
        if isinstance(expression, ir.IRSpawn):
            result_type = expression.call.typ
            result_size = "0" if result_type == VOID else f"sizeof({self.c_type(result_type)})"
            return CExpr(
                f"({self.c_type(expression.typ)}){{ .control = zy2_task_spawn(__zy2_spawn_{expression.spawn_id}, NULL, {result_size}) }}",
                [],
            )
        if isinstance(expression, ir.IRAwait):
            task = self.emit_expr(expression.task)
            prelude = list(task.prelude)
            if expression.typ == VOID:
                prelude.append(f"zy2_task_await_and_destroy(&({task.code}).control, NULL, 0);")
                return CExpr("((void)0)", prelude)
            result = self.temp("await")
            prelude.append(f"{self.c_type(expression.typ)} {result};")
            prelude.append(
                f"zy2_task_await_and_destroy(&({task.code}).control, &{result}, sizeof({result}));"
            )
            return CExpr(result, prelude)
        raise ValueError(f"unsupported IR expression {type(expression).__name__}")

    def emit_binary(self, expression: ir.IRBinary) -> CExpr:
        if expression.operator in {"==", "!="} and (
            isinstance(expression.left, ir.IRNull) or isinstance(expression.right, ir.IRNull)
        ):
            other = expression.right if isinstance(expression.left, ir.IRNull) else expression.left
            value = self.emit_expr(other)
            test = value.code + ".has_value"
            if expression.operator == "==":
                test = "!" + test
            return CExpr(f"({test})", value.prelude)
        left = self.emit_expr(expression.left)
        right = self.emit_expr(expression.right)
        prelude = left.prelude + right.prelude
        if expression.left.typ == STR and expression.operator in {"==", "!="}:
            comparison = f"strcmp({left.code}, {right.code}) == 0"
            if expression.operator == "!=":
                comparison = f"!({comparison})"
            return CExpr(f"({comparison})", prelude)
        return CExpr(f"({left.code} {expression.operator} {right.code})", prelude)

    def emit_call(self, expression: ir.IRCall, *, propagate: bool) -> CExpr:
        args: list[str] = []
        prelude: list[str] = []
        for arg in expression.args:
            value = self.emit_expr(arg)
            prelude.extend(value.prelude)
            args.append(value.code)
        if expression.target == "__zy2_get_args":
            list_type = self.c_type(expression.typ)
            return CExpr(
                f"({list_type}){{ .data = (const char**)(zy2_process_argc > 1 ? zy2_process_argv + 1 : NULL), "
                ".len = (uintptr_t)(zy2_process_argc > 1 ? zy2_process_argc - 1 : 0) }",
                prelude,
            )
        if expression.target == "__zy2_get_exe":
            return CExpr("(zy2_process_argc > 0 ? zy2_process_argv[0] : \"\")", prelude)
        if expression.target == "zy2_list_len":
            return CExpr(f"({args[0]}).len", prelude)
        if expression.target == "__zy2_list_get":
            list_value = self.temp("list")
            index_value = self.temp("index")
            result = self.temp("result")
            source_name = json.dumps(expression.span.source_name)
            prelude.extend(
                [
                    f"{self.c_type(expression.args[0].typ)} {list_value} = {args[0]};",
                    f"int32_t {index_value} = {args[1]};",
                    f"{self.result_type(expression.typ)} {result} = {{0}};",
                    f"if ({index_value} < 0 || (uintptr_t){index_value} >= {list_value}.len) {{",
                    f"    {result}.ok = false;",
                    f"    {result}.error = (zy2_Error){{ .message = \"List index out of range\", .source_file = {source_name}, .line = {expression.span.line}, .column = {expression.span.column} }};",
                    "} else {",
                    f"    {result}.ok = true;",
                    f"    {result}.value = {list_value}.data[{index_value}];",
                    "}",
                ]
            )
            return self.finish_throwing_result(expression, result, prelude, propagate)
        code = f"{expression.target}({', '.join(args)})"
        if expression.throws is None:
            return CExpr(code, prelude)
        result = self.temp("result")
        prelude.append(f"{self.result_type(expression.typ)} {result} = {code};")
        return self.finish_throwing_result(expression, result, prelude, propagate)

    def finish_throwing_result(
        self,
        expression: ir.IRCall,
        result: str,
        prelude: list[str],
        propagate: bool,
    ) -> CExpr:
        if propagate:
            if self.current_function and self.current_function.throws:
                current_result = self.result_type(self.current_function.return_type)
                prelude.append(f"if (!{result}.ok) return ({current_result}){{ .ok = false, .error = {result}.error }};")
            else:
                prelude.append(f"if (!{result}.ok) zy2_unhandled_error({result}.error);")
        result_code = "((void)0)" if expression.typ == VOID else f"{result}.value"
        return CExpr(result_code, prelude)

    def emit_catch(self, expression: ir.IRCatch) -> CExpr:
        if not isinstance(expression.value, ir.IRCall):
            raise ValueError("verified catch value is not a call")
        call = self.emit_call(expression.value, propagate=False)
        prelude = list(call.prelude)
        result_name = self.result_name_from_call_prelude(prelude)
        target = None
        if expression.typ != VOID:
            target = self.temp("recovered")
            prelude.append(f"{self.c_type(expression.typ)} {target} = {self.zero_value(expression.typ)};")
            prelude.append(f"if ({result_name}.ok) {{ {target} = {result_name}.value; }} else {{")
        else:
            prelude.append(f"if (!{result_name}.ok) {{")
        prelude.append(f"    zy2_Error {self.ident(expression.error_name)} = {result_name}.error;")
        prelude.append(f"    (void){self.ident(expression.error_name)};")
        self.catch_targets.append((target, expression.typ))
        try:
            handler = self.emit_block(expression.handler, 1)
        finally:
            self.catch_targets.pop()
        prelude.extend(handler)
        prelude.append("}")
        return CExpr("((void)0)" if target is None else target, prelude)

    @staticmethod
    def result_name_from_call_prelude(prelude: list[str]) -> str:
        for line in reversed(prelude):
            match = re.search(r"\s(__zy_result_\d+)\s*=", line)
            if match:
                return match.group(1)
        raise ValueError("throwing call did not create a result temporary")

    def emit_aggregate(self, typ: Type, values: tuple[ir.IRExpr, ...], names: list[str]) -> CExpr:
        prelude: list[str] = []
        fields: list[str] = []
        for name, item in zip(names, values):
            value = self.emit_expr(item)
            prelude.extend(value.prelude)
            fields.append(f".{name} = {value.code}")
        body = ", ".join(fields)
        return CExpr(f"({self.c_type(typ)}){{ {body} }}", prelude)

    def emit_list(self, expression: ir.IRList) -> CExpr:
        element = expression.typ.args[0] if isinstance(expression.typ, NamedType) else VOID
        if not expression.items:
            return CExpr(f"({self.c_type(expression.typ)}){{ .data = NULL, .len = 0 }}", [])
        prelude: list[str] = []
        values: list[str] = []
        for item in expression.items:
            value = self.emit_expr(item)
            prelude.extend(value.prelude)
            values.append(value.code)
        array = f"({self.c_type(element)}[]){{ {', '.join(values)} }}"
        return CExpr(
            f"({self.c_type(expression.typ)}){{ .data = {array}, .len = {len(values)} }}",
            prelude,
        )

    def result_type(self, value_type: Type) -> str:
        return self.type_name(self.result_marker(value_type))

    def c_type(self, typ: Type) -> str:
        if isinstance(typ, PrimitiveType):
            mapping = {
                "i8": "int8_t",
                "i16": "int16_t",
                "i32": "int32_t",
                "i64": "int64_t",
                "u8": "uint8_t",
                "u16": "uint16_t",
                "u32": "uint32_t",
                "u64": "uint64_t",
                "isize": "intptr_t",
                "usize": "uintptr_t",
                "f32": "float",
                "f64": "double",
                "bool": "bool",
                "str": "const char*",
                "void": "void",
                "Error": "zy2_Error",
            }
            return mapping[typ.name]
        if isinstance(typ, NamedType) and typ.name in self.structs:
            return self.struct_c_name(typ.name)
        return self.type_name(typ)

    def type_name(self, typ: Type) -> str:
        if isinstance(typ, OptionalType):
            return f"zy2_optional_{self.type_slug(typ.inner)}"
        if isinstance(typ, TupleType):
            return "zy2_tuple_" + "_".join(self.type_slug(item) for item in typ.items)
        if is_list(typ):
            return f"zy2_list_{self.type_slug(typ.args[0])}"
        if is_task(typ):
            return f"zy2_task_{self.type_slug(typ.args[0])}"
        if isinstance(typ, NamedType) and typ.name == "__Result":
            return f"zy2_result_{self.type_slug(typ.args[0])}"
        if isinstance(typ, NamedType) and typ.name in self.structs:
            return self.struct_c_name(typ.name)
        raise ValueError(f"type `{typ.display()}` has no generated C name")

    def type_slug(self, typ: Type) -> str:
        if isinstance(typ, PrimitiveType):
            return self.ident(typ.name)
        if isinstance(typ, NamedType):
            base = self.ident(typ.name)
            return base if not typ.args else base + "_" + "_".join(self.type_slug(arg) for arg in typ.args)
        if isinstance(typ, TupleType):
            return "tuple_" + "_".join(self.type_slug(item) for item in typ.items)
        if isinstance(typ, OptionalType):
            return "optional_" + self.type_slug(typ.inner)
        raise ValueError(f"cannot create type slug for `{typ.display()}`")

    def zero_value(self, typ: Type) -> str:
        if typ == STR:
            return "NULL"
        if typ == BOOL:
            return "false"
        if isinstance(typ, PrimitiveType):
            return "0"
        return f"({self.c_type(typ)}){{0}}"

    def temp(self, label: str) -> str:
        self.temp_counter += 1
        return f"__zy_{label}_{self.temp_counter}"

    @staticmethod
    def ident(value: str) -> str:
        return re.sub(r"[^A-Za-z0-9_]", "_", value)

    @staticmethod
    def struct_tag(name: str) -> str:
        return f"zy2_tag_{CBackend.ident(name)}"

    @staticmethod
    def struct_c_name(name: str) -> str:
        return f"zy2_struct_{CBackend.ident(name)}"
