from __future__ import annotations

from dataclasses import dataclass
import json
import re

from .. import ir
from ..types import (
    BOOL,
    ERROR,
    STR,
    VOID,
    FunctionType,
    NamedType,
    OptionalType,
    PrimitiveType,
    TupleType,
    Type,
    is_box,
    is_float,
    is_integer,
    is_list,
    is_numeric,
    is_signed_integer,
    is_unsigned_integer,
    is_task,
)


@dataclass
class CExpr:
    code: str
    prelude: list[str]
    owned: bool = False


class CBackend:
    name = "c"

    def __init__(self) -> None:
        self.program: ir.IRProgram | None = None
        self.structs: dict[str, ir.IRStructDef] = {}
        self.emitted_types: set[Type] = set()
        self.emitting_types: set[Type] = set()
        self.type_lines: list[str] = []
        self.temp_counter = 0
        self.current_function: ir.IRFunction | None = None
        self.catch_targets: list[tuple[str | None, Type]] = []
        self.spawn_sites: dict[int, ir.IRSpawn] = {}
        self.metadata_uses: set[tuple[str, str]] = set()
        self.managed_scopes: list[list[tuple[str, Type]]] = []
        self.loop_scope_depths: list[int] = []

    def emit(self, program: ir.IRProgram) -> str:
        self.program = program
        self.structs = {item.name: item for item in program.structs}
        self.emitted_types.clear()
        self.emitting_types.clear()
        self.type_lines.clear()
        self.temp_counter = 0
        self.metadata_uses.clear()
        self.spawn_sites = self.collect_spawn_sites(program)

        lines = ["// Generated by the ZyenLang 0.2 typed C backend."]
        if "threads" in program.features:
            lines.append("#define ZY2_ENABLE_THREADS 1")
        lines.extend(['#include "zy2_runtime.h"', ""])
        for struct in program.structs:
            lines.append(f"typedef struct {self.struct_tag(struct.name)} {self.struct_c_name(struct.name)};")
        if program.structs:
            lines.append("")

        for typ in self.collect_program_types(program):
            self.emit_type_definition(typ)
        lines.extend(self.type_lines)
        if self.type_lines:
            lines.append("")

        metadata_lines = self.emit_struct_metadata_tables()
        lines.extend(metadata_lines)
        if metadata_lines:
            lines.append("")

        for function in program.extern_functions:
            lines.append(self.extern_signature(function) + ";")
        if program.extern_functions:
            lines.append("")
        for function in program.functions:
            lines.append(self.function_signature(function) + ";")
        lines.append("")

        for spawn in self.spawn_sites.values():
            lines.extend(self.emit_spawn_helper(spawn))
            lines.append("")

        for function in program.functions:
            lines.extend(self.emit_function(function))
            lines.append("")

        main = next(item for item in program.functions if item.name == "main" and item.receiver_type is None)
        lines.extend(self.emit_main_wrapper(main))
        lines.append("")
        return "\n".join(lines)

    def collect_spawn_sites(self, program: ir.IRProgram) -> dict[int, ir.IRSpawn]:
        found: dict[int, ir.IRSpawn] = {}

        def expression(value: ir.IRExpr) -> None:
            if isinstance(value, ir.IRSpawn):
                found[value.spawn_id] = value
                expression(value.call)
            elif isinstance(value, ir.IRAwait):
                expression(value.task)
            elif isinstance(value, ir.IROptionalSome):
                expression(value.value)
            elif isinstance(value, ir.IRUnary):
                expression(value.operand)
            elif isinstance(value, ir.IRBinary):
                expression(value.left)
                expression(value.right)
            elif isinstance(value, ir.IRCast):
                expression(value.value)
            elif isinstance(value, ir.IRField):
                expression(value.receiver)
            elif isinstance(value, ir.IRIndirectCall):
                expression(value.callee)
                for arg in value.args:
                    expression(arg)
            elif isinstance(value, ir.IRCall):
                for arg in value.args:
                    expression(arg)
            elif isinstance(value, (ir.IRTuple, ir.IRList)):
                for item in value.items:
                    expression(item)
            elif isinstance(value, ir.IRStruct):
                for _, item in value.fields:
                    expression(item)
            elif isinstance(value, ir.IRStructMetadata):
                expression(value.receiver)
            elif isinstance(value, ir.IRBox):
                expression(value.value)
            elif isinstance(value, ir.IRBoxValue):
                expression(value.box)
            elif isinstance(value, ir.IRArcCount):
                expression(value.value)
            elif isinstance(value, ir.IRCatch):
                expression(value.value)
                block(value.handler)

        def statement(value: ir.IRStmt) -> None:
            if isinstance(value, ir.IRLet):
                expression(value.value)
            elif isinstance(value, (ir.IRReturn, ir.IRRecover)) and value.value is not None:
                expression(value.value)
            elif isinstance(value, ir.IRStop):
                expression(value.error)
            elif isinstance(value, ir.IRIf):
                expression(value.condition)
                block(value.then_block)
                if value.else_block:
                    block(value.else_block)
            elif isinstance(value, ir.IRIfLet):
                expression(value.value)
                block(value.then_block)
                if value.else_block:
                    block(value.else_block)
            elif isinstance(value, ir.IRWhile):
                expression(value.condition)
                block(value.body)
            elif isinstance(value, ir.IRAssign):
                expression(value.target)
                expression(value.value)
            elif isinstance(value, ir.IRExprStmt):
                expression(value.value)

        def block(value: ir.IRBlock) -> None:
            for item in value.statements:
                statement(item)

        for function in program.functions:
            block(function.body)
        return found

    def collect_program_types(self, program: ir.IRProgram) -> list[Type]:
        found: list[Type] = []
        seen: set[Type] = set()

        def add(typ: Type) -> None:
            if typ in seen:
                return
            seen.add(typ)
            found.append(typ)
            if isinstance(typ, NamedType):
                for arg in typ.args:
                    add(arg)
            elif isinstance(typ, TupleType):
                for item in typ.items:
                    add(item)
            elif isinstance(typ, OptionalType):
                add(typ.inner)
            elif isinstance(typ, FunctionType):
                for item in typ.params:
                    add(item)
                add(typ.return_type)

        def expression(value: ir.IRExpr) -> None:
            add(value.typ)
            if isinstance(value, ir.IROptionalSome):
                expression(value.value)
            elif isinstance(value, ir.IRUnary):
                expression(value.operand)
            elif isinstance(value, ir.IRBinary):
                expression(value.left)
                expression(value.right)
            elif isinstance(value, ir.IRCast):
                expression(value.value)
            elif isinstance(value, ir.IRField):
                expression(value.receiver)
            elif isinstance(value, ir.IRIndirectCall):
                expression(value.callee)
                for arg in value.args:
                    expression(arg)
            elif isinstance(value, ir.IRCall):
                if value.throws:
                    add(value.throws)
                    add(self.result_marker(value.typ))
                for arg in value.args:
                    expression(arg)
            elif isinstance(value, (ir.IRTuple, ir.IRList)):
                for item in value.items:
                    expression(item)
            elif isinstance(value, ir.IRStruct):
                for _, item in value.fields:
                    expression(item)
            elif isinstance(value, ir.IRStructMetadata):
                self.metadata_uses.add((value.struct_name, value.category))
                expression(value.receiver)
            elif isinstance(value, ir.IRBox):
                expression(value.value)
            elif isinstance(value, ir.IRBoxValue):
                expression(value.box)
            elif isinstance(value, ir.IRArcCount):
                expression(value.value)
            elif isinstance(value, ir.IRCatch):
                expression(value.value)
                block(value.handler)
            elif isinstance(value, ir.IRSpawn):
                expression(value.call)
            elif isinstance(value, ir.IRAwait):
                expression(value.task)

        def statement(value: ir.IRStmt) -> None:
            if isinstance(value, ir.IRLet):
                for typ in value.types:
                    add(typ)
                expression(value.value)
            elif isinstance(value, (ir.IRReturn, ir.IRRecover)) and value.value is not None:
                expression(value.value)
            elif isinstance(value, ir.IRStop):
                expression(value.error)
            elif isinstance(value, ir.IRIf):
                expression(value.condition)
                block(value.then_block)
                if value.else_block:
                    block(value.else_block)
            elif isinstance(value, ir.IRIfLet):
                expression(value.value)
                add(value.inner_type)
                block(value.then_block)
                if value.else_block:
                    block(value.else_block)
            elif isinstance(value, ir.IRWhile):
                expression(value.condition)
                block(value.body)
            elif isinstance(value, ir.IRAssign):
                expression(value.target)
                expression(value.value)
            elif isinstance(value, ir.IRExprStmt):
                expression(value.value)

        def block(value: ir.IRBlock) -> None:
            for item in value.statements:
                statement(item)

        for struct in program.structs:
            add(NamedType(struct.name))
            for field in struct.fields:
                add(field.typ)
                if field.default:
                    expression(field.default)
        for function in program.functions:
            add(function.return_type)
            if function.throws:
                add(function.throws)
                add(self.result_marker(function.return_type))
            for param in function.params:
                add(param.typ)
            block(function.body)
        for function in program.extern_functions:
            add(function.return_type)
            if function.throws:
                add(function.throws)
                add(self.result_marker(function.return_type))
            for param in function.params:
                add(param.typ)
        return found

    def result_marker(self, value_type: Type) -> NamedType:
        return NamedType("__Result", (value_type, ERROR))

    def emit_type_definition(self, typ: Type) -> None:
        if typ in self.emitted_types or isinstance(typ, PrimitiveType):
            return
        if typ in self.emitting_types:
            raise ValueError(f"recursive by-value type `{typ.display()}`")
        self.emitting_types.add(typ)
        try:
            if isinstance(typ, NamedType) and typ.name in self.structs:
                struct = self.structs[typ.name]
                for field in struct.fields:
                    self.emit_type_definition(field.typ)
                self.type_lines.append(f"struct {self.struct_tag(struct.name)} {{")
                for field in struct.fields:
                    self.type_lines.append(f"    {self.c_type(field.typ)} {self.ident(field.name)};")
                self.type_lines.append("};")
                self.type_lines.append("")
            elif isinstance(typ, FunctionType):
                for item in (*typ.params, typ.return_type):
                    if isinstance(item, FunctionType):
                        self.emit_type_definition(item)
                params = ", ".join(self.c_type(item) for item in typ.params) or "void"
                self.type_lines.append(
                    f"typedef {self.c_type(typ.return_type)} (*{self.type_name(typ)})({params});"
                )
                self.type_lines.append("")
            elif is_list(typ):
                element = typ.args[0]
                self.emit_type_definition(element)
                name = self.type_name(typ)
                storage = f"{name}_storage"
                release_item = self.release_stmt("storage->items[index]", element)
                retain_item = self.retain_expr("item", element)
                retain_old_item = self.retain_expr("old_items[index]", element)
                self.type_lines.extend(
                    [
                        f"typedef struct {storage} {{",
                        f"    {self.c_type(element)}* items;",
                        "    uintptr_t len;",
                        "    uintptr_t capacity;",
                        f"}} {storage};",
                        f"typedef struct {name} {{",
                        f"    {storage}* storage;",
                        f"    {self.c_type(element)}* borrowed_items;",
                        "    uintptr_t borrowed_len;",
                        "    zy2_ArcControl* owner;",
                        f"}} {name};",
                        "",
                        f"static inline ZY2_MAYBE_UNUSED void {name}_storage_drop(void* payload) {{",
                        f"    {storage}* storage = ({storage}*)payload;",
                        "    if (!storage) return;",
                        "    for (uintptr_t index = 0; index < storage->len; ++index) {",
                        f"        {release_item}",
                        "    }",
                        "    free(storage->items);",
                        "    free(storage);",
                        "}",
                        f"static inline ZY2_MAYBE_UNUSED {name} {name}_new(uintptr_t capacity) {{",
                        f"    {storage}* storage = ({storage}*)calloc(1, sizeof({storage}));",
                        "    if (!storage) zy2_arc_panic(\"cannot allocate List storage\");",
                        "    if (capacity > 0) {",
                        f"        storage->items = ({self.c_type(element)}*)calloc(capacity, sizeof({self.c_type(element)}));",
                        "        if (!storage->items) { free(storage); zy2_arc_panic(\"cannot allocate List data\"); }",
                        "        storage->capacity = capacity;",
                        "    }",
                        f"    return ({name}){{ .storage = storage, .owner = zy2_arc_new(storage, {name}_storage_drop) }};",
                        "}",
                        f"static inline ZY2_MAYBE_UNUSED {name} {name}_borrow({self.c_type(element)}* items, uintptr_t len) {{",
                        f"    return ({name}){{ .borrowed_items = items, .borrowed_len = len }};",
                        "}",
                        f"static inline ZY2_MAYBE_UNUSED {name} {name}_retain({name} value) {{",
                        "    zy2_arc_retain(value.owner);",
                        "    return value;",
                        "}",
                        f"static inline ZY2_MAYBE_UNUSED void {name}_release({name} value) {{",
                        "    zy2_arc_release(value.owner);",
                        "}",
                        f"static inline ZY2_MAYBE_UNUSED uintptr_t {name}_len({name} value) {{",
                        "    return value.storage ? value.storage->len : value.borrowed_len;",
                        "}",
                        f"static inline ZY2_MAYBE_UNUSED {self.c_type(element)}* {name}_items({name} value) {{",
                        "    return value.storage ? value.storage->items : value.borrowed_items;",
                        "}",
                        f"static inline ZY2_MAYBE_UNUSED void {name}_ensure_mutable({name}* value, uintptr_t extra) {{",
                        "    if (!value->owner) {",
                        f"        {self.c_type(element)}* old_items = value->borrowed_items;",
                        "        uintptr_t old_len = value->borrowed_len;",
                        "        uintptr_t initial = old_len + extra;",
                        "        if (initial < 4) initial = 4;",
                        f"        *value = {name}_new(initial);",
                        "        for (uintptr_t index = 0; index < old_len; ++index) {",
                        f"            value->storage->items[index] = {retain_old_item};",
                        "        }",
                        "        value->storage->len = old_len;",
                        "    }",
                        "    uintptr_t required = value->storage->len + extra;",
                        "    if (required <= value->storage->capacity) return;",
                        "    uintptr_t capacity = value->storage->capacity ? value->storage->capacity : 4;",
                        "    while (capacity < required) {",
                        "        if (capacity > UINTPTR_MAX / 2) zy2_arc_panic(\"List capacity overflow\");",
                        "        capacity *= 2;",
                        "    }",
                        f"    {self.c_type(element)}* grown = ({self.c_type(element)}*)realloc(value->storage->items, capacity * sizeof({self.c_type(element)}));",
                        "    if (!grown) zy2_arc_panic(\"cannot grow List\");",
                        "    value->storage->items = grown;",
                        "    value->storage->capacity = capacity;",
                        "}",
                        f"static inline ZY2_MAYBE_UNUSED void {name}_push_copy({name}* value, {self.c_type(element)} item) {{",
                        f"    {name}_ensure_mutable(value, 1);",
                        f"    value->storage->items[value->storage->len++] = {retain_item};",
                        "}",
                        f"static inline ZY2_MAYBE_UNUSED void {name}_set_copy({name}* value, uintptr_t index, {self.c_type(element)} item) {{",
                        f"    {name}_ensure_mutable(value, 0);",
                        f"    {self.release_stmt('value->storage->items[index]', element)}",
                        f"    value->storage->items[index] = {retain_item};",
                        "}",
                        f"static inline ZY2_MAYBE_UNUSED void {name}_clear({name}* value) {{",
                        "    if (!value->owner) {",
                        f"        *value = {name}_new(0);",
                        "        return;",
                        "    }",
                        "    for (uintptr_t index = 0; index < value->storage->len; ++index) {",
                        f"        {self.release_stmt('value->storage->items[index]', element)}",
                        "    }",
                        "    value->storage->len = 0;",
                        "}",
                        "",
                    ]
                )
            elif is_task(typ):
                self.emit_type_definition(typ.args[0])
                self.type_lines.extend(
                    [
                        f"typedef struct {self.type_name(typ)} {{",
                        "    zy2_Task* control;",
                        f"}} {self.type_name(typ)};",
                        "",
                    ]
                )
            elif is_box(typ):
                inner = typ.args[0]
                self.emit_type_definition(inner)
                name = self.type_name(typ)
                self.type_lines.extend(
                    [
                        f"typedef struct {name} {{",
                        f"    {self.c_type(inner)}* data;",
                        "    zy2_ArcControl* owner;",
                        f"}} {name};",
                        "",
                        f"static inline ZY2_MAYBE_UNUSED {name} {name}_new({self.c_type(inner)} value) {{",
                        f"    {self.c_type(inner)}* payload = ({self.c_type(inner)}*)malloc(sizeof({self.c_type(inner)}));",
                        "    if (!payload) zy2_arc_panic(\"cannot allocate Box payload\");",
                        "    *payload = value;",
                        f"    return ({name}){{ .data = payload, .owner = zy2_arc_new(payload, free) }};",
                        "}",
                        f"static inline ZY2_MAYBE_UNUSED {name} {name}_retain({name} value) {{",
                        "    zy2_arc_retain(value.owner);",
                        "    return value;",
                        "}",
                        f"static inline ZY2_MAYBE_UNUSED void {name}_release({name} value) {{",
                        "    zy2_arc_release(value.owner);",
                        "}",
                        "",
                    ]
                )
            elif isinstance(typ, OptionalType):
                self.emit_type_definition(typ.inner)
                self.type_lines.extend(
                    [
                        f"typedef struct {self.type_name(typ)} {{",
                        "    bool has_value;",
                        f"    {self.c_type(typ.inner)} value;",
                        f"}} {self.type_name(typ)};",
                        "",
                    ]
                )
            elif isinstance(typ, TupleType):
                for item in typ.items:
                    self.emit_type_definition(item)
                self.type_lines.append(f"typedef struct {self.type_name(typ)} {{")
                for index, item in enumerate(typ.items):
                    self.type_lines.append(f"    {self.c_type(item)} item_{index};")
                self.type_lines.append(f"}} {self.type_name(typ)};")
                self.type_lines.append("")
            elif isinstance(typ, NamedType) and typ.name == "__Result":
                value_type = typ.args[0]
                self.emit_type_definition(value_type)
                self.type_lines.append(f"typedef struct {self.type_name(typ)} {{")
                self.type_lines.append("    bool ok;")
                if value_type != VOID:
                    self.type_lines.append(f"    {self.c_type(value_type)} value;")
                self.type_lines.append("    zy2_Error error;")
                self.type_lines.append(f"}} {self.type_name(typ)};")
                self.type_lines.append("")
            else:
                raise ValueError(f"C backend does not yet support `{typ.display()}`")
            self.emitted_types.add(typ)
        finally:
            self.emitting_types.remove(typ)

    def emit_function(self, function: ir.IRFunction) -> list[str]:
        self.current_function = function
        self.managed_scopes = []
        self.loop_scope_depths = []
        try:
            lines = [self.function_signature(function) + " {"]
            for param in function.params:
                lines.append(f"    (void){self.ident(param.name)};")
            managed_params = tuple(param for param in function.params if self.is_managed(param.typ))
            lines.extend(self.emit_block(function.body, 1, managed_params=managed_params))
            if function.return_type == VOID and not function.throws:
                lines.append("    return;")
            elif function.return_type == VOID and function.throws:
                result = self.result_type(function.return_type)
                lines.append(f"    return ({result}){{ .ok = true }};")
            lines.append("}")
            return lines
        finally:
            self.current_function = None

    def function_signature(self, function: ir.IRFunction) -> str:
        return_type = self.result_type(function.return_type) if function.throws else self.c_type(function.return_type)
        params = ", ".join(f"{self.c_type(param.typ)} {self.ident(param.name)}" for param in function.params)
        if not params:
            params = "void"
        prefix = "static ZY2_MAYBE_UNUSED " if function.visibility == "private" else ""
        return f"{prefix}{return_type} {function.c_name}({params})"

    def extern_signature(self, function: ir.IRExternFunction) -> str:
        return_type = self.result_type(function.return_type) if function.throws else self.c_type(function.return_type)
        params = ", ".join(f"{self.c_type(param.typ)} {self.ident(param.name)}" for param in function.params)
        if not params:
            params = "void"
        return f"extern {return_type} {function.c_name}({params})"

    def emit_spawn_helper(self, expression: ir.IRSpawn) -> list[str]:
        result_type = expression.call.typ
        lines = [f"static void __zy2_spawn_{expression.spawn_id}(void* context, void* result) {{", "    (void)context;"]
        if result_type == VOID:
            lines.append("    (void)result;")
            lines.append(f"    {expression.call.target}();")
        else:
            lines.append(f"    *(({self.c_type(result_type)}*)result) = {expression.call.target}();")
        lines.append("}")
        return lines

    def emit_main_wrapper(self, main: ir.IRFunction) -> list[str]:
        lines = ["int main(int argc, char** argv) {", "    zy2_set_process_args(argc, argv);"]
        if main.throws:
            lines.append(f"    {self.result_type(main.return_type)} result = {main.c_name}();")
            lines.append("    if (!result.ok) zy2_unhandled_error(result.error);")
            lines.append("    int exit_code = (int)result.value;")
        else:
            lines.append(f"    int exit_code = (int){main.c_name}();")
        lines.append("    if (!zy2_arc_assert_clean()) return 101;")
        lines.append("    return exit_code;")
        lines.append("}")
        return lines

    def emit_block(
        self,
        block: ir.IRBlock,
        indent: int,
        *,
        managed_params: tuple[ir.IRParam, ...] = (),
    ) -> list[str]:
        self.managed_scopes.append([])
        lines: list[str] = []
        pad = "    " * indent
        try:
            for param in managed_params:
                name = self.ident(param.name)
                lines.append(f"{pad}{name} = {self.retain_expr(name, param.typ)};")
                self.managed_scopes[-1].append((name, param.typ))
            for statement in block.statements:
                lines.extend(self.emit_statement(statement, indent))
            lines.extend(self.cleanup_lines(len(self.managed_scopes) - 1, indent))
            return lines
        finally:
            self.managed_scopes.pop()

    def emit_statement(self, statement: ir.IRStmt, indent: int) -> list[str]:
        pad = "    " * indent
        if isinstance(statement, ir.IRLet):
            value = self.emit_expr(statement.value)
            lines = [pad + line for line in value.prelude]
            if len(statement.names) == 1:
                typ = statement.types[0]
                name = self.ident(statement.names[0])
                initializer = self.take_or_retain(value, typ)
                lines.append(f"{pad}{self.c_type(typ)} {name} = {initializer};")
                lines.append(f"{pad}(void){name};")
                if self.is_managed(typ):
                    self.managed_scopes[-1].append((name, typ))
            else:
                temp = self.temp("tuple")
                lines.append(f"{pad}{self.c_type(statement.value.typ)} {temp} = {value.code};")
                for index, (name, typ) in enumerate(zip(statement.names, statement.types)):
                    lines.append(f"{pad}{self.c_type(typ)} {self.ident(name)} = {temp}.item_{index};")
                    lines.append(f"{pad}(void){self.ident(name)};")
            return lines
        if isinstance(statement, ir.IRReturn):
            if statement.value is None:
                cleanup = self.cleanup_lines(0, indent)
                if self.current_function and self.current_function.throws:
                    return cleanup + [f"{pad}return ({self.result_type(VOID)}){{ .ok = true }};"]
                return cleanup + [f"{pad}return;"]
            value = self.emit_expr(statement.value)
            lines = [pad + line for line in value.prelude]
            return_type = self.current_function.return_type if self.current_function else statement.value.typ
            temp = self.temp("return")
            result_value = self.take_or_retain(value, return_type)
            lines.append(f"{pad}{self.c_type(return_type)} {temp} = {result_value};")
            lines.extend(self.cleanup_lines(0, indent))
            if self.current_function and self.current_function.throws:
                result = self.result_type(self.current_function.return_type)
                lines.append(f"{pad}return ({result}){{ .ok = true, .value = {temp} }};")
            else:
                lines.append(f"{pad}return {temp};")
            return lines
        if isinstance(statement, ir.IRStop):
            value = self.emit_expr(statement.error)
            lines = [pad + line for line in value.prelude]
            if not self.current_function or not self.current_function.throws:
                raise ValueError("verified IR contains stop in a non-throwing function")
            result = self.result_type(self.current_function.return_type)
            error_temp = self.temp("error")
            lines.append(f"{pad}zy2_Error {error_temp} = {value.code};")
            lines.extend(self.cleanup_lines(0, indent))
            lines.append(f"{pad}return ({result}){{ .ok = false, .error = {error_temp} }};")
            return lines
        if isinstance(statement, ir.IRRecover):
            if not self.catch_targets:
                raise ValueError("verified IR contains recover outside catch")
            target, expected = self.catch_targets[-1]
            if statement.value is None:
                return [f"{pad}/* recovered void error */"]
            value = self.emit_expr(statement.value)
            lines = [pad + line for line in value.prelude]
            if target is None or expected == VOID:
                lines.append(f"{pad}(void)({value.code});")
            else:
                lines.append(f"{pad}{target} = {self.take_or_retain(value, expected)};")
            return lines
        if isinstance(statement, ir.IRIf):
            condition = self.emit_expr(statement.condition)
            lines = [pad + line for line in condition.prelude]
            lines.append(f"{pad}if {self.control_condition(condition.code)} {{")
            lines.extend(self.emit_block(statement.then_block, indent + 1))
            if statement.else_block is not None:
                lines.append(f"{pad}}} else {{")
                lines.extend(self.emit_block(statement.else_block, indent + 1))
            lines.append(f"{pad}}}")
            return lines
        if isinstance(statement, ir.IRIfLet):
            value = self.emit_expr(statement.value)
            lines = [pad + line for line in value.prelude]
            temp = self.temp("optional")
            lines.append(f"{pad}{self.c_type(statement.value.typ)} {temp} = {value.code};")
            lines.append(f"{pad}if ({temp}.has_value) {{")
            lines.append(f"{pad}    {self.c_type(statement.inner_type)} {self.ident(statement.name)} = {temp}.value;")
            lines.append(f"{pad}    (void){self.ident(statement.name)};")
            lines.extend(self.emit_block(statement.then_block, indent + 1))
            if statement.else_block is not None:
                lines.append(f"{pad}}} else {{")
                lines.extend(self.emit_block(statement.else_block, indent + 1))
            lines.append(f"{pad}}}")
            return lines
        if isinstance(statement, ir.IRWhile):
            condition = self.emit_expr(statement.condition)
            lines = [f"{pad}while (true) {{"]
            lines.extend("    " + pad + line for line in condition.prelude)
            lines.append(f"{pad}    if (!{self.control_condition(condition.code)}) break;")
            self.loop_scope_depths.append(len(self.managed_scopes))
            try:
                lines.extend(self.emit_block(statement.body, indent + 1))
            finally:
                self.loop_scope_depths.pop()
            lines.append(f"{pad}}}")
            return lines
        if isinstance(statement, ir.IRAssign):
            target = self.emit_expr(statement.target)
            value = self.emit_expr(statement.value)
            lines = [pad + line for line in target.prelude + value.prelude]
            if self.is_managed(statement.target.typ):
                temp = self.temp("assign")
                lines.append(
                    f"{pad}{self.c_type(statement.target.typ)} {temp} = {self.take_or_retain(value, statement.target.typ)};"
                )
                lines.append(f"{pad}{self.release_stmt(target.code, statement.target.typ)}")
                lines.append(f"{pad}{target.code} = {temp};")
            else:
                lines.append(f"{pad}{target.code} = {value.code};")
            return lines
        if isinstance(statement, ir.IRBreak):
            if not self.loop_scope_depths:
                raise ValueError("verified IR contains break outside a loop")
            return self.cleanup_lines(self.loop_scope_depths[-1], indent) + [f"{pad}break;"]
        if isinstance(statement, ir.IRContinue):
            if not self.loop_scope_depths:
                raise ValueError("verified IR contains continue outside a loop")
            return self.cleanup_lines(self.loop_scope_depths[-1], indent) + [f"{pad}continue;"]
        if isinstance(statement, ir.IRExprStmt):
            value = self.emit_expr(statement.value)
            lines = [pad + line for line in value.prelude]
            if self.is_managed(statement.value.typ) and value.owned:
                temp = self.temp("discard")
                lines.append(f"{pad}{self.c_type(statement.value.typ)} {temp} = {value.code};")
                lines.append(f"{pad}{self.release_stmt(temp, statement.value.typ)}")
            else:
                lines.append(f"{pad}(void)({value.code});")
            return lines
        raise ValueError(f"unsupported IR statement {type(statement).__name__}")

    @staticmethod
    def control_condition(code: str) -> str:
        value = code.strip()
        if value.startswith("(") and value.endswith(")"):
            depth = 0
            for index, char in enumerate(value):
                if char == "(":
                    depth += 1
                elif char == ")":
                    depth -= 1
                    if depth == 0 and index != len(value) - 1:
                        break
            else:
                if depth == 0:
                    return value
        return f"({value})"

    def emit_expr(self, expression: ir.IRExpr) -> CExpr:
        if isinstance(expression, ir.IRInt):
            if is_unsigned_integer(expression.typ):
                return CExpr(f"UINT64_C({expression.value})", [])
            return CExpr(str(expression.value), [])
        if isinstance(expression, ir.IRString):
            return CExpr(json.dumps(expression.value), [])
        if isinstance(expression, ir.IRBool):
            return CExpr("true" if expression.value else "false", [])
        if isinstance(expression, ir.IRNull):
            return CExpr(f"({self.c_type(expression.typ)}){{ .has_value = false }}", [])
        if isinstance(expression, ir.IROptionalSome):
            value = self.emit_expr(expression.value)
            return CExpr(
                f"({self.c_type(expression.typ)}){{ .has_value = true, .value = {value.code} }}",
                value.prelude,
            )
        if isinstance(expression, ir.IRName):
            return CExpr(self.ident(expression.name), [])
        if isinstance(expression, ir.IRUnary):
            operand = self.emit_expr(expression.operand)
            return CExpr(f"({expression.operator}{operand.code})", operand.prelude)
        if isinstance(expression, ir.IRBinary):
            return self.emit_binary(expression)
        if isinstance(expression, ir.IRCast):
            return self.emit_cast(expression)
        if isinstance(expression, ir.IRField):
            receiver = self.emit_expr(expression.receiver)
            return CExpr(f"({receiver.code}).{self.ident(expression.name)}", receiver.prelude)
        if isinstance(expression, ir.IRFunctionRef):
            return CExpr(expression.target, [])
        if isinstance(expression, ir.IRIndirectCall):
            return self.emit_indirect_call(expression)
        if isinstance(expression, ir.IRCall):
            return self.emit_call(expression, propagate=True)
        if isinstance(expression, ir.IRTuple):
            return self.emit_aggregate(expression.typ, expression.items, [f"item_{i}" for i in range(len(expression.items))])
        if isinstance(expression, ir.IRList):
            return self.emit_list(expression)
        if isinstance(expression, ir.IRStruct):
            values = tuple(value for _, value in expression.fields)
            names = [self.ident(name) for name, _ in expression.fields]
            return self.emit_aggregate(expression.typ, values, names)
        if isinstance(expression, ir.IRStructMetadata):
            return self.emit_struct_metadata(expression)
        if isinstance(expression, ir.IRBox):
            value = self.emit_expr(expression.value)
            return CExpr(
                f"{self.type_name(expression.typ)}_new({value.code})",
                value.prelude,
                owned=True,
            )
        if isinstance(expression, ir.IRBoxValue):
            box = self.emit_expr(expression.box)
            if box.owned:
                box_temp = self.temp("box")
                value_temp = self.temp("box_value")
                prelude = list(box.prelude)
                prelude.append(f"{self.c_type(expression.box.typ)} {box_temp} = {box.code};")
                prelude.append(f"{self.c_type(expression.typ)} {value_temp} = *{box_temp}.data;")
                prelude.append(self.release_stmt(box_temp, expression.box.typ))
                return CExpr(value_temp, prelude)
            return CExpr(f"*({box.code}).data", box.prelude)
        if isinstance(expression, ir.IRArcCount):
            value = self.emit_expr(expression.value)
            if value.owned:
                box_temp = self.temp("box")
                count_temp = self.temp("arc_count")
                prelude = list(value.prelude)
                prelude.append(f"{self.c_type(expression.value.typ)} {box_temp} = {value.code};")
                prelude.append(f"uintptr_t {count_temp} = (uintptr_t)zy2_arc_strong_count({box_temp}.owner);")
                prelude.append(self.release_stmt(box_temp, expression.value.typ))
                return CExpr(count_temp, prelude)
            return CExpr(f"zy2_arc_strong_count(({value.code}).owner)", value.prelude)
        if isinstance(expression, ir.IRCatch):
            return self.emit_catch(expression)
        if isinstance(expression, ir.IRSpawn):
            result_type = expression.call.typ
            result_size = "0" if result_type == VOID else f"sizeof({self.c_type(result_type)})"
            return CExpr(
                f"({self.c_type(expression.typ)}){{ .control = zy2_task_spawn(__zy2_spawn_{expression.spawn_id}, NULL, {result_size}) }}",
                [],
            )
        if isinstance(expression, ir.IRAwait):
            task = self.emit_expr(expression.task)
            prelude = list(task.prelude)
            if expression.typ == VOID:
                prelude.append(f"zy2_task_await_and_destroy(&({task.code}).control, NULL, 0);")
                return CExpr("((void)0)", prelude)
            result = self.temp("await")
            prelude.append(f"{self.c_type(expression.typ)} {result};")
            prelude.append(
                f"zy2_task_await_and_destroy(&({task.code}).control, &{result}, sizeof({result}));"
            )
            return CExpr(result, prelude)
        raise ValueError(f"unsupported IR expression {type(expression).__name__}")

    def emit_struct_metadata_tables(self) -> list[str]:
        lines: list[str] = []
        for struct_name, category in sorted(self.metadata_uses):
            items = self.struct_metadata_items(struct_name, category)
            if not items:
                continue
            values = ", ".join(json.dumps(item) for item in items)
            lines.append(f"static const char* {self.struct_metadata_name(struct_name, category)}[] = {{ {values} }};")
        return lines

    def emit_struct_metadata(self, expression: ir.IRStructMetadata) -> CExpr:
        receiver = self.emit_expr(expression.receiver)
        prelude = list(receiver.prelude)
        prelude.append(f"(void)({receiver.code});")
        items = self.struct_metadata_items(expression.struct_name, expression.category)
        if not items:
            return CExpr(f"{self.type_name(expression.typ)}_borrow(NULL, 0)", prelude)
        name = self.struct_metadata_name(expression.struct_name, expression.category)
        return CExpr(
            f"{self.type_name(expression.typ)}_borrow(({self.c_type(STR)}*){name}, {len(items)})",
            prelude,
        )

    def struct_metadata_items(self, struct_name: str, category: str) -> tuple[str, ...]:
        if category == "attributes":
            return tuple(field.name for field in self.structs[struct_name].fields)
        assert self.program is not None
        return tuple(
            function.name
            for function in self.program.functions
            if isinstance(function.receiver_type, NamedType) and function.receiver_type.name == struct_name
        )

    def struct_metadata_name(self, struct_name: str, category: str) -> str:
        return f"zy2_meta_{self.ident(struct_name)}_{category}"

    def emit_cast(self, expression: ir.IRCast) -> CExpr:
        value = self.emit_expr(expression.value)
        if expression.typ == expression.value.typ:
            return value
        if expression.typ == STR and expression.value.typ == BOOL:
            return CExpr(f"(({value.code}) ? \"true\" : \"false\")", value.prelude)
        if (
            expression.typ == STR
            and isinstance(expression.value.typ, OptionalType)
            and expression.value.typ.inner == STR
        ):
            optional_value = self.temp("optional_text")
            prelude = list(value.prelude)
            prelude.append(f"{self.c_type(expression.value.typ)} {optional_value} = {value.code};")
            return CExpr(
                f"({optional_value}.has_value ? {optional_value}.value : \"null\")",
                prelude,
            )
        if expression.typ == STR and is_numeric(expression.value.typ):
            buffer = self.temp("number_text")
            prelude = list(value.prelude)
            prelude.append(f"char {buffer}[64];")
            if is_float(expression.value.typ):
                precision = "9" if expression.value.typ == PrimitiveType("f32") else "17"
                prelude.append(
                    f"snprintf({buffer}, sizeof({buffer}), \"%.{precision}g\", (double)({value.code}));"
                )
            elif is_signed_integer(expression.value.typ):
                prelude.append(
                    f"snprintf({buffer}, sizeof({buffer}), \"%lld\", (long long)({value.code}));"
                )
            else:
                prelude.append(
                    f"snprintf({buffer}, sizeof({buffer}), \"%llu\", (unsigned long long)({value.code}));"
                )
            return CExpr(buffer, prelude)
        if expression.typ == BOOL and is_numeric(expression.value.typ):
            return CExpr(f"(({value.code}) != 0)", value.prelude)
        return CExpr(f"(({self.c_type(expression.typ)})({value.code}))", value.prelude)

    def emit_binary(self, expression: ir.IRBinary) -> CExpr:
        if expression.operator in {"==", "!="} and (
            isinstance(expression.left, ir.IRNull) or isinstance(expression.right, ir.IRNull)
        ):
            other = expression.right if isinstance(expression.left, ir.IRNull) else expression.left
            value = self.emit_expr(other)
            test = value.code + ".has_value"
            if expression.operator == "==":
                test = "!" + test
            return CExpr(f"({test})", value.prelude)
        left = self.emit_expr(expression.left)
        right = self.emit_expr(expression.right)
        prelude = left.prelude + right.prelude
        if is_box(expression.left.typ) and expression.operator in {"==", "!="}:
            left_code = left.code
            right_code = right.code
            if left.owned:
                left_code = self.temp("box_left")
                prelude.append(f"{self.c_type(expression.left.typ)} {left_code} = {left.code};")
            if right.owned:
                right_code = self.temp("box_right")
                prelude.append(f"{self.c_type(expression.right.typ)} {right_code} = {right.code};")
            result = self.temp("box_compare")
            comparison = f"({left_code}).owner == ({right_code}).owner"
            if expression.operator == "!=":
                comparison = f"!({comparison})"
            prelude.append(f"bool {result} = ({comparison});")
            if left.owned:
                prelude.append(self.release_stmt(left_code, expression.left.typ))
            if right.owned:
                prelude.append(self.release_stmt(right_code, expression.right.typ))
            return CExpr(result, prelude)
        if expression.left.typ == STR and expression.operator in {"==", "!="}:
            return self.emit_structural_equality(expression, left, right)
        if expression.operator in {"==", "!="} and self.is_structural_equality_type(expression.left.typ):
            return self.emit_structural_equality(expression, left, right)
        if (
            expression.operator in {"<", "<=", ">", ">=", "==", "!="}
            and is_numeric(expression.left.typ)
            and is_numeric(expression.right.typ)
            and expression.left.typ != expression.right.typ
        ):
            return self.emit_mixed_numeric_comparison(expression, left, right)
        return CExpr(f"({left.code} {expression.operator} {right.code})", prelude)

    def is_structural_equality_type(self, typ: Type) -> bool:
        return (
            isinstance(typ, OptionalType)
            or isinstance(typ, TupleType)
            or (isinstance(typ, NamedType) and typ.name in self.structs)
        )

    def emit_structural_equality(self, expression: ir.IRBinary, left: CExpr, right: CExpr) -> CExpr:
        left_temp = self.temp("equal_left")
        right_temp = self.temp("equal_right")
        prelude = list(left.prelude)
        prelude.append(f"{self.c_type(expression.left.typ)} {left_temp} = {left.code};")
        prelude.extend(right.prelude)
        prelude.append(f"{self.c_type(expression.right.typ)} {right_temp} = {right.code};")
        comparison = self.equality_code(expression.left.typ, left_temp, right_temp)
        if expression.operator == "!=":
            comparison = f"!({comparison})"
        return CExpr(f"({comparison})", prelude)

    def equality_code(self, typ: Type, left: str, right: str) -> str:
        if typ == STR:
            return (
                f"(({left}) == ({right}) || "
                f"(({left}) != NULL && ({right}) != NULL && strcmp(({left}), ({right})) == 0))"
            )
        if typ == BOOL or is_numeric(typ):
            return f"(({left}) == ({right}))"
        if isinstance(typ, FunctionType):
            return f"(({left}) == ({right}))"
        if is_box(typ):
            return f"(({left}).owner == ({right}).owner)"
        if isinstance(typ, OptionalType):
            values_equal = self.equality_code(typ.inner, f"({left}).value", f"({right}).value")
            return (
                f"((!({left}).has_value && !({right}).has_value) || "
                f"(({left}).has_value && ({right}).has_value && ({values_equal})))"
            )
        if isinstance(typ, TupleType):
            comparisons = [
                self.equality_code(item, f"({left}).item_{index}", f"({right}).item_{index}")
                for index, item in enumerate(typ.items)
            ]
            return "(" + " && ".join(comparisons) + ")" if comparisons else "true"
        if isinstance(typ, NamedType) and typ.name in self.structs:
            comparisons = [
                self.equality_code(
                    field.typ,
                    f"({left}).{self.ident(field.name)}",
                    f"({right}).{self.ident(field.name)}",
                )
                for field in self.structs[typ.name].fields
            ]
            return "(" + " && ".join(comparisons) + ")" if comparisons else "true"
        raise ValueError(f"type `{typ.display()}` has no equality code")

    def emit_mixed_numeric_comparison(self, expression: ir.IRBinary, left: CExpr, right: CExpr) -> CExpr:
        left_temp = self.temp("compare_left")
        right_temp = self.temp("compare_right")
        prelude = list(left.prelude)
        prelude.append(f"{self.c_type(expression.left.typ)} {left_temp} = {left.code};")
        prelude.extend(right.prelude)
        prelude.append(f"{self.c_type(expression.right.typ)} {right_temp} = {right.code};")

        if is_integer(expression.left.typ) and is_integer(expression.right.typ):
            left_signed = is_signed_integer(expression.left.typ)
            right_signed = is_signed_integer(expression.right.typ)
            if left_signed != right_signed:
                operator_names = {
                    "==": "eq",
                    "!=": "ne",
                    "<": "lt",
                    "<=": "le",
                    ">": "gt",
                    ">=": "ge",
                }
                operator = expression.operator
                if left_signed:
                    signed_value = left_temp
                    unsigned_value = right_temp
                else:
                    signed_value = right_temp
                    unsigned_value = left_temp
                    operator = {"<": ">", "<=": ">=", ">": "<", ">=": "<="}.get(operator, operator)
                helper = f"zy2_compare_i64_u64_{operator_names[operator]}"
                return CExpr(
                    f"{helper}((int64_t)({signed_value}), (uint64_t)({unsigned_value}))",
                    prelude,
                )
            common = "int64_t" if left_signed else "uint64_t"
            return CExpr(
                f"(({common})({left_temp}) {expression.operator} ({common})({right_temp}))",
                prelude,
            )

        return CExpr(
            f"((double)({left_temp}) {expression.operator} (double)({right_temp}))",
            prelude,
        )

    def emit_call(self, expression: ir.IRCall, *, propagate: bool) -> CExpr:
        args: list[str] = []
        prelude: list[str] = []
        owned_arg_releases: list[str] = []
        for arg in expression.args:
            value = self.emit_expr(arg)
            prelude.extend(value.prelude)
            if self.is_managed(arg.typ) and value.owned:
                temp = self.temp("argument")
                prelude.append(f"{self.c_type(arg.typ)} {temp} = {value.code};")
                args.append(temp)
                owned_arg_releases.append(self.release_stmt(temp, arg.typ))
            else:
                args.append(value.code)
        if expression.target == "__zy2_get_args":
            return CExpr(
                f"{self.type_name(expression.typ)}_borrow((const char**)(zy2_process_argc > 1 ? zy2_process_argv + 1 : NULL), "
                "(uintptr_t)(zy2_process_argc > 1 ? zy2_process_argc - 1 : 0))",
                prelude,
            )
        if expression.target == "__zy2_get_exe":
            return CExpr("(zy2_process_argc > 0 ? zy2_process_argv[0] : \"\")", prelude)
        if expression.target == "zy2_list_len":
            result_value = self.temp("list_len")
            prelude.append(f"uintptr_t {result_value} = {self.type_name(expression.args[0].typ)}_len({args[0]});")
            prelude.extend(owned_arg_releases)
            return CExpr(result_value, prelude)
        if expression.target == "zy2_list_capacity":
            result_value = self.temp("list_capacity")
            list_name = self.type_name(expression.args[0].typ)
            prelude.append(
                f"uintptr_t {result_value} = ({args[0]}).storage ? ({args[0]}).storage->capacity : ({args[0]}).borrowed_len;"
            )
            prelude.extend(owned_arg_releases)
            return CExpr(result_value, prelude)
        if expression.target == "zy2_list_is_empty":
            result_value = self.temp("list_empty")
            prelude.append(f"bool {result_value} = {self.type_name(expression.args[0].typ)}_len({args[0]}) == 0;")
            prelude.extend(owned_arg_releases)
            return CExpr(result_value, prelude)
        if expression.target in {"__zy2_list_push", "__zy2_list_clear"}:
            list_name = self.type_name(expression.args[0].typ)
            if expression.target == "__zy2_list_push":
                prelude.append(f"{list_name}_push_copy(&({args[0]}), {args[1]});")
            else:
                prelude.append(f"{list_name}_clear(&({args[0]}));")
            prelude.extend(owned_arg_releases)
            return CExpr("((void)0)", prelude)
        if expression.target == "__zy2_list_get":
            list_value = self.temp("list")
            index_value = self.temp("index")
            result = self.temp("result")
            source_name = json.dumps(expression.span.source_name)
            list_name = self.type_name(expression.args[0].typ)
            element_type = expression.typ
            prelude.extend(
                [
                    f"{self.c_type(expression.args[0].typ)} {list_value} = {args[0]};",
                    f"int32_t {index_value} = {args[1]};",
                    f"{self.result_type(expression.typ)} {result} = {{0}};",
                    f"if ({index_value} < 0 || (uintptr_t){index_value} >= {list_name}_len({list_value})) {{",
                    f"    {result}.ok = false;",
                    f"    {result}.error = (zy2_Error){{ .message = \"List index out of range\", .source_file = {source_name}, .line = {expression.span.line}, .column = {expression.span.column} }};",
                    "} else {",
                    f"    {result}.ok = true;",
                    f"    {result}.value = {self.retain_expr(f'{list_name}_items({list_value})[{index_value}]', element_type)};",
                    "}",
                ]
            )
            prelude.extend(owned_arg_releases)
            return self.finish_throwing_result(expression, result, prelude, propagate)
        if expression.target == "__zy2_list_set":
            list_value = args[0]
            index_value = self.temp("index")
            result = self.temp("result")
            source_name = json.dumps(expression.span.source_name)
            list_name = self.type_name(expression.args[0].typ)
            prelude.extend(
                [
                    f"int32_t {index_value} = {args[1]};",
                    f"{self.result_type(VOID)} {result} = {{0}};",
                    f"if ({index_value} < 0 || (uintptr_t){index_value} >= {list_name}_len({list_value})) {{",
                    f"    {result}.ok = false;",
                    f"    {result}.error = (zy2_Error){{ .message = \"List index out of range\", .source_file = {source_name}, .line = {expression.span.line}, .column = {expression.span.column} }};",
                    "} else {",
                    f"    {list_name}_set_copy(&({list_value}), (uintptr_t){index_value}, {args[2]});",
                    f"    {result}.ok = true;",
                    "}",
                ]
            )
            prelude.extend(owned_arg_releases)
            return self.finish_throwing_result(expression, result, prelude, propagate)
        if expression.target in {"__zy2_list_pop", "__zy2_list_remove"}:
            list_value = args[0]
            result = self.temp("result")
            source_name = json.dumps(expression.span.source_name)
            list_type = expression.args[0].typ
            list_name = self.type_name(list_type)
            element_type = expression.typ
            index_value = self.temp("index")
            if expression.target == "__zy2_list_pop":
                index_setup = f"uintptr_t {index_value} = {list_name}_len({list_value}) - 1;"
                invalid = f"{list_name}_len({list_value}) == 0"
                message = "cannot pop from an empty List"
            else:
                prelude.append(f"int32_t {index_value} = {args[1]};")
                index_setup = ""
                invalid = f"{index_value} < 0 || (uintptr_t){index_value} >= {list_name}_len({list_value})"
                message = "List index out of range"
            prelude.extend(
                [
                    f"{self.result_type(element_type)} {result} = {{0}};",
                    f"if ({invalid}) {{",
                    f"    {result}.ok = false;",
                    f"    {result}.error = (zy2_Error){{ .message = {json.dumps(message)}, .source_file = {source_name}, .line = {expression.span.line}, .column = {expression.span.column} }};",
                    "} else {",
                ]
            )
            if index_setup:
                prelude.append(f"    {index_setup}")
            prelude.extend(
                [
                    f"    {list_name}_ensure_mutable(&({list_value}), 0);",
                    f"    {result}.value = ({list_value}).storage->items[{index_value}];",
                    f"    uintptr_t tail = ({list_value}).storage->len - (uintptr_t){index_value} - 1;",
                    "    if (tail > 0) {",
                    f"        memmove(&({list_value}).storage->items[{index_value}], &({list_value}).storage->items[{index_value} + 1], tail * sizeof({self.c_type(element_type)}));",
                    "    }",
                    f"    ({list_value}).storage->len -= 1;",
                    f"    ({list_value}).storage->items[({list_value}).storage->len] = {self.zero_value(element_type)};",
                    f"    {result}.ok = true;",
                    "}",
                ]
            )
            prelude.extend(owned_arg_releases)
            return self.finish_throwing_result(expression, result, prelude, propagate)
        code = f"{expression.target}({', '.join(args)})"
        if expression.throws is None:
            if owned_arg_releases:
                if expression.typ == VOID:
                    prelude.append(f"(void)({code});")
                    prelude.extend(owned_arg_releases)
                    return CExpr("((void)0)", prelude)
                result_value = self.temp("call")
                prelude.append(f"{self.c_type(expression.typ)} {result_value} = {code};")
                prelude.extend(owned_arg_releases)
                return CExpr(result_value, prelude, owned=self.is_managed(expression.typ))
            return CExpr(code, prelude, owned=self.is_managed(expression.typ))
        result = self.temp("result")
        prelude.append(f"{self.result_type(expression.typ)} {result} = {code};")
        prelude.extend(owned_arg_releases)
        return self.finish_throwing_result(expression, result, prelude, propagate)

    def emit_indirect_call(self, expression: ir.IRIndirectCall) -> CExpr:
        callee = self.emit_expr(expression.callee)
        callee_temp = self.temp("callback")
        prelude = list(callee.prelude)
        prelude.append(f"{self.c_type(expression.callee.typ)} {callee_temp} = {callee.code};")
        prelude.append(
            f"if (!{callee_temp}) zy2_panic_at({json.dumps(expression.span.source_name)}, "
            f"{expression.span.line}, {expression.span.column}, \"attempted to call an empty function value\");"
        )
        args: list[str] = []
        for arg in expression.args:
            value = self.emit_expr(arg)
            prelude.extend(value.prelude)
            args.append(value.code)
        return CExpr(f"{callee_temp}({', '.join(args)})", prelude)

    def finish_throwing_result(
        self,
        expression: ir.IRCall,
        result: str,
        prelude: list[str],
        propagate: bool,
    ) -> CExpr:
        if propagate:
            if self.current_function and self.current_function.throws:
                current_result = self.result_type(self.current_function.return_type)
                prelude.append(f"if (!{result}.ok) {{")
                prelude.extend("    " + line for line in self.cleanup_lines(0, 0))
                prelude.append(f"    return ({current_result}){{ .ok = false, .error = {result}.error }};")
                prelude.append("}")
            else:
                prelude.append(f"if (!{result}.ok) {{")
                prelude.extend("    " + line for line in self.cleanup_lines(0, 0))
                prelude.append(f"    zy2_unhandled_error({result}.error);")
                prelude.append("}")
        result_code = "((void)0)" if expression.typ == VOID else f"{result}.value"
        return CExpr(result_code, prelude, owned=self.is_managed(expression.typ))

    def emit_catch(self, expression: ir.IRCatch) -> CExpr:
        if not isinstance(expression.value, ir.IRCall):
            raise ValueError("verified catch value is not a call")
        call = self.emit_call(expression.value, propagate=False)
        prelude = list(call.prelude)
        result_name = self.result_name_from_call_prelude(prelude)
        target = None
        if expression.typ != VOID:
            target = self.temp("recovered")
            prelude.append(f"{self.c_type(expression.typ)} {target} = {self.zero_value(expression.typ)};")
            prelude.append(f"if ({result_name}.ok) {{ {target} = {result_name}.value; }} else {{")
        else:
            prelude.append(f"if (!{result_name}.ok) {{")
        prelude.append(f"    zy2_Error {self.ident(expression.error_name)} = {result_name}.error;")
        prelude.append(f"    (void){self.ident(expression.error_name)};")
        self.catch_targets.append((target, expression.typ))
        try:
            handler = self.emit_block(expression.handler, 1)
        finally:
            self.catch_targets.pop()
        prelude.extend(handler)
        prelude.append("}")
        return CExpr(
            "((void)0)" if target is None else target,
            prelude,
            owned=self.is_managed(expression.typ),
        )

    @staticmethod
    def result_name_from_call_prelude(prelude: list[str]) -> str:
        for line in reversed(prelude):
            match = re.search(r"\s(__zy_result_\d+)\s*=", line)
            if match:
                return match.group(1)
        raise ValueError("throwing call did not create a result temporary")

    def emit_aggregate(self, typ: Type, values: tuple[ir.IRExpr, ...], names: list[str]) -> CExpr:
        prelude: list[str] = []
        fields: list[str] = []
        for name, item in zip(names, values):
            value = self.emit_expr(item)
            prelude.extend(value.prelude)
            fields.append(f".{name} = {value.code}")
        body = ", ".join(fields)
        return CExpr(f"({self.c_type(typ)}){{ {body} }}", prelude)

    def emit_list(self, expression: ir.IRList) -> CExpr:
        element = expression.typ.args[0] if isinstance(expression.typ, NamedType) else VOID
        list_name = self.type_name(expression.typ)
        result = self.temp("list")
        prelude: list[str] = [f"{self.c_type(expression.typ)} {result} = {list_name}_new({len(expression.items)});"]
        for item in expression.items:
            value = self.emit_expr(item)
            prelude.extend(value.prelude)
            if self.is_managed(element) and value.owned:
                item_temp = self.temp("list_item")
                prelude.append(f"{self.c_type(element)} {item_temp} = {value.code};")
                prelude.append(f"{list_name}_push_copy(&{result}, {item_temp});")
                prelude.append(self.release_stmt(item_temp, element))
            else:
                prelude.append(f"{list_name}_push_copy(&{result}, {value.code});")
        return CExpr(result, prelude, owned=True)

    def result_type(self, value_type: Type) -> str:
        return self.type_name(self.result_marker(value_type))

    def c_type(self, typ: Type) -> str:
        if isinstance(typ, PrimitiveType):
            mapping = {
                "i8": "int8_t",
                "i16": "int16_t",
                "i32": "int32_t",
                "i64": "int64_t",
                "u8": "uint8_t",
                "u16": "uint16_t",
                "u32": "uint32_t",
                "u64": "uint64_t",
                "isize": "intptr_t",
                "usize": "uintptr_t",
                "f32": "float",
                "f64": "double",
                "bool": "bool",
                "str": "const char*",
                "void": "void",
                "Error": "zy2_Error",
            }
            return mapping[typ.name]
        if isinstance(typ, NamedType) and typ.name in self.structs:
            return self.struct_c_name(typ.name)
        if isinstance(typ, FunctionType):
            return self.type_name(typ)
        return self.type_name(typ)

    def type_name(self, typ: Type) -> str:
        if isinstance(typ, OptionalType):
            return f"zy2_optional_{self.type_slug(typ.inner)}"
        if isinstance(typ, TupleType):
            return "zy2_tuple_" + "_".join(self.type_slug(item) for item in typ.items)
        if isinstance(typ, FunctionType):
            params = "_".join(self.type_slug(item) for item in typ.params) or "void"
            return f"zy2_fn_{params}_to_{self.type_slug(typ.return_type)}"
        if is_list(typ):
            return f"zy2_list_{self.type_slug(typ.args[0])}"
        if is_task(typ):
            return f"zy2_task_{self.type_slug(typ.args[0])}"
        if is_box(typ):
            return f"zy2_box_{self.type_slug(typ.args[0])}"
        if isinstance(typ, NamedType) and typ.name == "__Result":
            return f"zy2_result_{self.type_slug(typ.args[0])}"
        if isinstance(typ, NamedType) and typ.name in self.structs:
            return self.struct_c_name(typ.name)
        raise ValueError(f"type `{typ.display()}` has no generated C name")

    def type_slug(self, typ: Type) -> str:
        if isinstance(typ, PrimitiveType):
            return self.ident(typ.name)
        if isinstance(typ, NamedType):
            base = self.ident(typ.name)
            return base if not typ.args else base + "_" + "_".join(self.type_slug(arg) for arg in typ.args)
        if isinstance(typ, TupleType):
            return "tuple_" + "_".join(self.type_slug(item) for item in typ.items)
        if isinstance(typ, OptionalType):
            return "optional_" + self.type_slug(typ.inner)
        if isinstance(typ, FunctionType):
            params = "_".join(self.type_slug(item) for item in typ.params) or "void"
            return f"fn_{params}_to_{self.type_slug(typ.return_type)}"
        raise ValueError(f"cannot create type slug for `{typ.display()}`")

    def zero_value(self, typ: Type) -> str:
        if typ == STR:
            return "NULL"
        if typ == BOOL:
            return "false"
        if isinstance(typ, FunctionType):
            return "NULL"
        if isinstance(typ, PrimitiveType):
            return "0"
        return f"({self.c_type(typ)}){{0}}"

    @staticmethod
    def is_managed(typ: Type) -> bool:
        return is_box(typ) or is_list(typ)

    def retain_expr(self, code: str, typ: Type) -> str:
        if is_box(typ):
            return f"{self.type_name(typ)}_retain({code})"
        if is_list(typ):
            return f"{self.type_name(typ)}_retain({code})"
        return code

    def release_stmt(self, code: str, typ: Type) -> str:
        if is_box(typ):
            return f"{self.type_name(typ)}_release({code});"
        if is_list(typ):
            return f"{self.type_name(typ)}_release({code});"
        return f"(void)({code});"

    def take_or_retain(self, value: CExpr, typ: Type) -> str:
        if not self.is_managed(typ) or value.owned:
            return value.code
        return self.retain_expr(value.code, typ)

    def cleanup_lines(self, start: int, indent: int) -> list[str]:
        pad = "    " * indent
        lines: list[str] = []
        for scope in reversed(self.managed_scopes[start:]):
            for name, typ in reversed(scope):
                lines.append(f"{pad}{self.release_stmt(name, typ)}")
        return lines

    def temp(self, label: str) -> str:
        self.temp_counter += 1
        return f"__zy_{label}_{self.temp_counter}"

    @staticmethod
    def ident(value: str) -> str:
        return re.sub(r"[^A-Za-z0-9_]", "_", value)

    @staticmethod
    def struct_tag(name: str) -> str:
        return f"zy2_tag_{CBackend.ident(name)}"

    @staticmethod
    def struct_c_name(name: str) -> str:
        return f"zy2_struct_{CBackend.ident(name)}"
