[package]
name = "zyenlang-examples"
version = "0.3.0"
zyen = ">=0.3.0"

[build]
default-target = "tour"
target-dir = "target"

[targets.tour]
kind = "bin"
entry = "language_tour.zy"
output-name = "zyenlang-tour"

[targets.language-guide]
kind = "bin"
entry = "language_reference.zy"

[targets.file-tree]
kind = "bin"
entry = "file_tree.zy"

[targets.gui-basic]
kind = "bin"
entry = "gui_basic.zy"

[targets.gui-button]
kind = "bin"
entry = "gui_widgets.zy"

[targets.path]
kind = "bin"
entry = "path_basic.zy"

[targets.struct-list]
kind = "bin"
entry = "struct_list.zy"

[targets.task]
kind = "bin"
entry = "task_basic.zy"

[targets.thread]
kind = "bin"
entry = "thread_basic.zy"

[targets.system-info]
kind = "bin"
entry = "system_info.zy"

[targets.http-server]
kind = "bin"
entry = "http_server.zy"

[dependencies]
