ZLC_MODULE(tk_native)
ZLC_HEADER("tk_native.h")
ZLC_SOURCE("tk_native.c")
ZLC_LIB_LINUX("dl")

ZLC_FN(begin, zl_tk_begin, int, ZLC_PARAM(path, str))
ZLC_FN(open, zl_tk_open, int, ZLC_PARAM(title, str), ZLC_PARAM(width, int), ZLC_PARAM(height, int))
ZLC_FN(window, zl_tk_window, int, ZLC_PARAM(title, str), ZLC_PARAM(width, int), ZLC_PARAM(height, int))
ZLC_FN(bg, zl_tk_bg, int, ZLC_PARAM(color, str))
ZLC_FN(clear, zl_tk_clear, int, ZLC_PARAM(color, str))
ZLC_FN(line, zl_tk_line, int, ZLC_PARAM(x1, int), ZLC_PARAM(y1, int), ZLC_PARAM(x2, int), ZLC_PARAM(y2, int), ZLC_PARAM(color, str), ZLC_PARAM(width, int))
ZLC_FN(rect, zl_tk_rect, int, ZLC_PARAM(x, int), ZLC_PARAM(y, int), ZLC_PARAM(width, int), ZLC_PARAM(height, int), ZLC_PARAM(color, str))
ZLC_FN(rect_outline, zl_tk_rect_outline, int, ZLC_PARAM(x, int), ZLC_PARAM(y, int), ZLC_PARAM(width, int), ZLC_PARAM(height, int), ZLC_PARAM(color, str), ZLC_PARAM(line_width, int))
ZLC_FN(circle, zl_tk_circle, int, ZLC_PARAM(x, int), ZLC_PARAM(y, int), ZLC_PARAM(radius, int), ZLC_PARAM(color, str))
ZLC_FN(circle_outline, zl_tk_circle_outline, int, ZLC_PARAM(x, int), ZLC_PARAM(y, int), ZLC_PARAM(radius, int), ZLC_PARAM(color, str), ZLC_PARAM(line_width, int))
ZLC_FN(text, zl_tk_text, int, ZLC_PARAM(x, int), ZLC_PARAM(y, int), ZLC_PARAM(text, str), ZLC_PARAM(color, str), ZLC_PARAM(size, int))
ZLC_FN(font_text, zl_tk_font_text, int, ZLC_PARAM(font_path, str), ZLC_PARAM(base_size, int), ZLC_PARAM(x, int), ZLC_PARAM(y, int), ZLC_PARAM(text, str), ZLC_PARAM(color, str), ZLC_PARAM(size, int))
ZLC_FN(font_text_width, zl_tk_font_text_width, int, ZLC_PARAM(font_path, str), ZLC_PARAM(base_size, int), ZLC_PARAM(text, str), ZLC_PARAM(size, int))
ZLC_FN(codeview, zl_tk_codeview, int, ZLC_PARAM(x, int), ZLC_PARAM(y, int), ZLC_PARAM(width, int), ZLC_PARAM(height, int), ZLC_PARAM(first_line, int), ZLC_PARAM(line_height, int), ZLC_PARAM(char_width, int), ZLC_PARAM(size, int), ZLC_PARAM(stamp, int), ZLC_PARAM(lines_path, str))
ZLC_FN(codeview_text, zl_tk_codeview_text, int, ZLC_PARAM(x, int), ZLC_PARAM(y, int), ZLC_PARAM(width, int), ZLC_PARAM(height, int), ZLC_PARAM(first_line, int), ZLC_PARAM(line_height, int), ZLC_PARAM(char_width, int), ZLC_PARAM(size, int), ZLC_PARAM(stamp, int), ZLC_PARAM(lines, str))
ZLC_FN(image, zl_tk_image, int, ZLC_PARAM(path, str), ZLC_PARAM(x, int), ZLC_PARAM(y, int))
ZLC_FN(script, zl_tk_script, str)
ZLC_FN(show, zl_tk_show, int)
ZLC_FN(show_for, zl_tk_show_for, int, ZLC_PARAM(ms, int))
ZLC_FN(session_open, zl_tk_session_open, int, ZLC_PARAM(title, str), ZLC_PARAM(width, int), ZLC_PARAM(height, int), ZLC_PARAM(session_dir, str))
ZLC_FN(session_begin_frame, zl_tk_session_begin_frame, int)
ZLC_FN(session_redraw, zl_tk_session_redraw, int)
ZLC_FN(session_set_fps, zl_tk_session_set_fps, int, ZLC_PARAM(fps, int))
ZLC_FN(session_next_event, zl_tk_session_next_event, str, ZLC_PARAM(timeout_ms, int))
ZLC_FN(session_pickdir, zl_tk_session_pickdir, int)
ZLC_FN(session_close, zl_tk_session_close, int)
ZLC_FN(session_char_w, zl_tk_session_char_w, int)
ZLC_FN(session_line_h, zl_tk_session_line_h, int)
ZLC_FN(event_kind, zl_tk_event_kind, int, ZLC_PARAM(event, str))
ZLC_FN(event_x, zl_tk_event_x, int, ZLC_PARAM(event, str))
ZLC_FN(event_y, zl_tk_event_y, int, ZLC_PARAM(event, str))
